### ISSUE TITLE
Add the IDIAP gpu in the queue list

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/gridtk#5]
The --queue option does not have the queue gpu; only 'all.q', 'q1d', 'q1w', 'q1m', 'q1dm', 'q1wm'.

I think is a good idea to have this list in a text file, so it is easy to edit.

**Comment by anjos** [comment]
A python program **is** a text file - why add a parser?

**Comment by tiagofrepereira2012** [comment]
I'm proposing nothing complex, just simple text file with one queue per line.

The parsing is one line of code.
```
queues = [o.rstrip("\n") for o in open("queues.txt").readlines()]
```
The variable `queues` will replace the list of queues that are in the `submit` and `resubmit` subparsers.

**Comment by anjos** [comment]
Why is that superior to a global variable?

**Comment by siebenkopf** [comment]
I agree with Andre. There is no need to have an external text file for the queues, unless you need to update that rapidly, e.g., using a script. As the queue names are pretty stable, just write them into a variable.

But, thanks for letting me know. Feel free to update the list (as I don't know the Idiap queues anymore).

**Comment by tiagofrepereira2012** [comment]
Done, thanks for the feedback :-)
