### ISSUE TITLE
Need support for qsub parameter for SGE variant - estmem

### ISSUE THREAD

**Issue by sc-jumper** [bioidiap/gridtk#7]
The variant of SGE that we use requires the attributes "hvmem" (which is included in the current version) and "estmem" which is not included.  I couldn't find a more graceful way to fix this so I added the attribute to the "def qsub" in tools.py.

def qsub(command, queue=None, cwd=True, name=None, deps=[], stdout='',
    stderr='', env=[], array=None, context='grid', hostname=None,
    memfree=None, hvmem=None, estmem=None, pe_opt=None, io_big=False):

Along with the following code in the method body.
 if estmem: scmd += ['-l', 'estmem=%s' % estmem]
...immediately following hvmem update...

**Comment by siebenkopf** [comment]
You are welcome to adapt the SGE to your system. 
GridTK is adapted to work with the SGE at Idiap, and honestly, it has never been tested outside Idiap, and I am glad that is seems to work. However, please do so in your own fork.
